### ISSUE TITLE
GPIO Buttons service not working

### ISSUE THREAD

**Issue by iwishitwassummer** [splitti/oled_phoniebox#3]
Hi,

thanks again for the project.
I installed the OLED and it worked fine. However I just realized that the GPIO button are not working any longer. I started the script on the oled directory and upon running all works fine. I choose option 2, the replacement.
I'll try and set up the service again, let's see

**Comment by iwishitwassummer** [comment]
Added service manually, pointing to gpio-button.py in oled_phoniebox folder, all working now

**Comment by carver79** [comment]
Same thing here - what exactly need to be done?

some info:
```
pi@raspberrypi:~ $ sudo systemctl status phoniebox-gpio-buttons
● phoniebox-gpio-buttons.service - Phoniebox GPIO Buttons Service
   Loaded: loaded (/etc/systemd/system/phoniebox-gpio-buttons.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2019-03-14 22:58:49 GMT; 26s ago
  Process: 16192 ExecStart=/home/pi/RPi-Jukebox-RFID/scripts/gpio-buttons.py (code=exited, status=1/FAILURE)
 Main PID: 16192 (code=exited, status=1/FAILURE)

Mar 14 22:58:49 raspberrypi systemd[1]: phoniebox-gpio-buttons.service: Unit entered failed state.
Mar 14 22:58:49 raspberrypi systemd[1]: phoniebox-gpio-buttons.service: Failed with result 'exit-code'.
Mar 14 22:58:49 raspberrypi systemd[1]: phoniebox-gpio-buttons.service: Service hold-off time over, scheduling restart.
Mar 14 22:58:49 raspberrypi systemd[1]: Stopped Phoniebox GPIO Buttons Service.
Mar 14 22:58:49 raspberrypi systemd[1]: phoniebox-gpio-buttons.service: Start request repeated too quickly.
Mar 14 22:58:49 raspberrypi systemd[1]: Failed to start Phoniebox GPIO Buttons Service.
Mar 14 22:58:49 raspberrypi systemd[1]: phoniebox-gpio-buttons.service: Unit entered failed state.
Mar 14 22:58:49 raspberrypi systemd[1]: phoniebox-gpio-buttons.service: Failed with result 'exit-code'.
```

**Comment by iwishitwassummer** [comment]
Hi,
You have to install the service manually now. 
Follow Autostart instructions from phoniebox setup 
https://github.com/MiczFlor/RPi-Jukebox-RFID/wiki/CONFIGURE-stretch#auto-start-the-phoniebox

Use the gpio button service only. 

I used the script in the oled folder instead of the phoniebox. Hence you have to modify the paths accordingly. 

I think I deleted the existing service before excusing the new one. 
Hope this helps
Cheers



> Am 14.03.2019 um 23:49 schrieb carver79 <notifications@github.com>:
> 
> Same thing here - what exactly need to be done?
> 
>
