### ISSUE TITLE
Always on start screen when a track is played

### ISSUE THREAD

**Issue by Josephraclure42** [splitti/oled_phoniebox#4]
Hello, 

The installation of oled_phoniebox succeeded on my phoniebox, but when a song is played I always have the "start" screen . When I press buttons I have the right images, also when I shutdown the raspberry but I don't have the song info when it is played . I chose "full" config, and I have another ssd1306 with another phoniebox that works well, so I assume there's no issue about that . 
I tried to stop and start the oled_phoniebox service, and reinstall .
Per haps the link between oled_phoniebox and mpd is not right ? 

Thanks for this cool project !

**Comment by splitti** [comment]
Hi Jose,

if possible: please try the display with the SD-Card of the other Phoniebox. Maybe there is an issue on starting.
Try to restart the service after booting the pi:
`sudo service oled_phoniebox restart`

And finally, if nothing helps, please sent the Info of the following command:
`sudo service oled_phoniebox status`

It would be nice, if you share your Pics here with a finished Phoniebox with display ;-)

**Comment by Josephraclure42** [comment]
Thanks for your help!
The display works with another SD card, and the restart does not change anything unfortunately :(
Here is what I have when I ask for service status : 
 oled_phoniebox.service - OLED Phoniebox Display Service
   Loaded: loaded (/etc/systemd/oled_phoniebox.service; enabled; vendor preset:
   Active: active (running) since Sat 2019-04-06 13:01:39 BST; 1min 33s ago
 Main PID: 1547 (python3)
   CGroup: /system.slice/oled_phoniebox.service
           └─1547 /usr/bin/python3 /home/pi/oled_phoniebox/./oled_phoniebox.py
Apr 06 13:01:39 MERLAUDIO systemd[1]: Started OLED Phoniebox Display Service.

I'm a kind of newbie, is there a way to completely uninstall the service and then reinstall it ? 
I will post photos of phonieboxes when finished, I still have to add earphones plug :)

Thank you !
