### ISSUE TITLE
Installation of python-imaging fails on debian buster

### ISSUE THREAD

**Issue by SirUli** [splitti/oled_phoniebox#5]
On Debian buster the installation of python-imaging fails as it isn't available anymore. The replacement seems to be python-pil, you might want to update that [here](https://github.com/splitti/oled_phoniebox/blob/master/scripts/install/o4p_installer.sh#L220) as a replacement generally since it is available in all "older" distros as well.

Cheers,
Uli

**Comment by splitti** [comment]
Thank you very much, i have noticed your info. I will investiage more time in the next days, maybe weeks.
What happens with the installation, is there a problem? Did you fix the installer by yourself?

**Comment by EliEquitania** [comment]
Es scheint, dass das Laden der Bibliothek nichts ausmacht, ich kann keine Auswirkung des fehlenden Packetes sehen.

**Comment by splitti** [comment]
The repositry is fixed, thank you for your invest!
