### ISSUE TITLE
OLED Phoniebox Display Service fails after trying to start

### ISSUE THREAD

**Issue by sglock** [splitti/oled_phoniebox#6]
Hi, first off all thank you for the hard work you put into your project. Unfortunately I can't get the OLED display to work. Checked with i2c tools if OLED display is even found but that isn't the problem. After starting or restarting the service i get the following status error message

pi@phoniepi:~ $ sudo service oled_phoniebox status
● oled_phoniebox.service - OLED Phoniebox Display Service
   Loaded: loaded (/etc/systemd/oled_phoniebox.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2020-01-12 21:47:14 CET; 9min ago
  Process: 959 ExecStart=/usr/bin/python3 /home/pi/oled_phoniebox/./oled_phoniebox.py (code=exited, status=1/FAILURE)
 Main PID: 959 (code=exited, status=1/FAILURE)

Jan 12 21:47:14 phoniepi python3[959]:     self._serial_interface.data(data)
Jan 12 21:47:14 phoniepi python3[959]:   File "/usr/local/lib/python3.7/dist-packages/luma/core/interface/serial.py", line 119, in data
Jan 12 21:47:14 phoniepi python3[959]:     write(list(data[i:i + block_size]))
Jan 12 21:47:14 phoniepi python3[959]:   File "/usr/local/lib/python3.7/dist-packages/luma/core/interface/serial.py", line 128, in _write_large_block
Jan 12 21:47:14 phoniepi python3[959]:     self._bus.i2c_rdwr(self._i2c_msg_write(self._addr, [self._data_mode] + data))
Jan 12 21:47:14 phoniepi python3[959]:   File "/usr/local/lib/python3.7/dist-packages/smbus2/smbus2.py", line 637, in i2c_rdwr
Jan 12 21:47:14 phoniepi python3[959]:     ioctl(self.fd, I2C_RDWR, ioctl_data)
Jan 12 21:47:14 phoniepi python3[959]: OSError: [Errno 121] Remote I/O error
Jan 12 21:47:14 phoniepi systemd[1]: oled_phoniebox.service: Main process exited, code=exited, status=1/FAILURE
Jan 12 21:47:14 phoniepi systemd[1]: oled_phoniebox.service: Failed with result 'exit-code'.

Since I am a noob I was wondering if you have any sugesstion what I might have done wrong.

**Comment by splitti** [comment]
Hi sglock,

mostly it is becaue of blocked GPIOs The OSError: [Errno 121] Remote I/O error indicates that an I2C device is not connected to the bus. Did you replace the gpio-buttons-Service on installation? If not, check if the shut-Variable is set in the gpio-buttons.py.
The GPIOs 4 and 17 should not be used by any other application!

Try this, to check:
`sudo service phoniebox-gpio-buttons stop`
`sudo service oled_phoniebox start`

**Comment by sglock** [comment]
Hi splitti,
thx for the quick answer and shame on me for not responding in time. Since a had to reinstall a couple of times I got the system working now but still no luck with the display. I forgot to mention that I am using the RC522 RFID Reader. GPIO 4 and 17 are not in use. Still  no Luck with the service.

Maybe you can check again if you can tell me what to do to get it working.

pi@phoniepi:~ $ sudo service phoniebox-gpio-buttons stop
pi@phoniepi:~ $ sudo service oled_phoniebox start
pi@phoniepi:~ $ sudo service oled_phoniebox status
● oled_phoniebox.service - OLED Phoniebox Display Service
   Loaded: loaded (/etc/systemd/oled_phoniebox.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2020-01-16 22:18:04 CET; 3s ago
  Process: 1782 ExecStart=/usr/bin/python3 /home/pi/oled_phoniebox/./oled_phoniebox.py (code=exited, status=1/FAILURE)
 Main PID: 1782 (code=exited, status=1/FAILURE)

Jan 16 22:18:04 phoniepi python3[1782]:     self._serial_interface.data(data)
Jan 16 22:18:04 phoniepi python3[1782]:   File "/usr/local/lib/python3.7/dist-packages/luma/core/interface/serial.py", line 119, in data
Jan 16 22:18:04 phoniepi python3[1782]:     write(list(data[i:i + block_size]))
Jan 16 22:18:04 phoniepi python3[1782]:   File "/usr/local/lib/python3.7/dist-packages/luma/core/interface/serial.py", line 128, in _write_large_block
Jan 16 22:18:04 phoniepi python3[1782]:     self._bus.i2c_rdwr(self._i2c_msg_write(self._addr, [self._data_mode] + data))
Jan 16 22:18:04 phoniepi python3[1782]:   File "/usr/local/lib/python3.7/dist-packages/smbus2/smbus2.py", line 637, in i2c_rdwr
Jan 16 22:18:04 phoniepi python3[1782]:     ioctl(self.fd, I2C_RDWR, ioctl_data)
Jan 16 22:18:04 phoniepi python3[1782]: OSError: [Errno 121] Remote I/O error
Jan 16 22:18:04 phoniepi systemd[1]: oled_phoniebox.service: Main process exited, code=exited, status=1/FAILURE
Jan 16 22:18:04 phoniepi systemd[1]: oled_phoniebox.service: Failed with result 'exit-code'.

**Comment by splitti** [comment]
That Looks Like a Problem with the connection. Maybe a Cable is broken.

Did you also make a reinstallation for the Display? Which gpio Option did you usw?

**Comment by sglock** [comment]
Changed all cables, did reinstall the display, chose option 2 connection with gpios as your instructions:

VDD | 5V / Pin 4
GND | Ground / Pin 6
SCK | GPIO 3 / Pin 5
SDA | GPIO 2 / Pin 3

I don't think there is a problem with the display. If I check via it2tools i get the following results:

Display connected:
> pi@phoniepi:~ $ i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- 3c -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --
>
Display disconnected:
>pi@phoniepi:~ $ i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --
>
Seems to me that the display is recognized.
Don't know what else to check ....

**Comment by splitti** [comment]
There are three possibilities i think:

1. The GPIO is blocked by any other Applikation
2. The Display ist defect
3. Anything was changed @ Python. I will Test the Last Option as soon as possible.

**Comment by sglock** [comment]
Hi Splitti,
just wanted to tell you that after receiving a new display today and wiring it up .... surprise .... everything works as it should. Thanx for your guidance an effort.
