### ISSUE TITLE
Appening in /boot/config.txt not working properly for me

### ISSUE THREAD

**Issue by hrueppert** [splitti/oled_phoniebox#9]
I'm installing a Phoniebox with Hifiberry Miniamp from the scratch using your documentation.

Everything works fine.

After installing your OLED installer i get no sound anymore. 
After checking all files i see, that the append in the /boot/config.txt was not properly.

The first line was directly append without a linebreak after the last parameter in the config.txt.

Looking like this:
dtoverlay=hifiberry-dacdtparam=i2c1=on
dtparam=i2c_arm=on
dtparam=i2c_arm_baudrate=400000

I test it several times on a blank sd card and get everytime the same result.

Maybe it's possible just to add a line break before append the first parameter. Thank you,

**Comment by splitti** [comment]
fixed

**Comment by hrueppert** [comment]
thank you
